#!/usr/bin/env ruby

SPECS = ["language/and_spec.rb"]

if ARGV[0].nil?
  puts "Please pass a ruby interpreter that can be tested and supports recieving code via -e"
  exit
end

@test_count = 0
@fails = 0
def check msg
  info = yield

  #CALL EXTERNAL
  ###################################
  call = "#{ARGV[0]} -e '#{info[:code]}' > /tmp/output"
  `#{call}`
  ###################################

  call_results = File.read("/tmp/output").split("\n")
  #$stderr.puts call_results.inspect
  
  results_clone = info[:results].dup

  info[:results].each_with_index do |result, index|
    exp = nil
    case result
    when "be_nil"
      exp = -> (x) { x == "nil" }
    when "== nil"
      exp = -> (x) { x == "nil" }
    when "== false"
      exp = -> (x) { x == "false" }
    when "== 1"
      exp = -> (x) { x == "1" }
    when "== 2"
      exp = -> (x) { x == "2" }

    when "== \"yes\""
      exp = -> (x) { x == "\"yes\"" }
    else
      raise "Unknown when test: #{result.inspect}"
    end

    if exp
      info[:results][index] = exp.call(call_results[index])
    end
  end

  #outcome = info[:results].reduce(true) {|s, e| s and e}
  info[:results].each_with_index do |result, index|
    if result == false
      $stderr.puts "\n\n"
      $stderr.puts "======================================================="
      $stderr.puts "Failed: #{msg}"
      $stderr.puts "Check #{index}"
      $stderr.puts "Check #{results_clone[index]}"
      $stderr.puts "-------------------------------------------------------"
      $stderr.puts info[:code]
      $stderr.puts "======================================================="
      $stderr.puts "\n"
      #exit
      @fails += 1
    else
      @test_count += 1
    end
  end

  $stderr.puts "+Passed [#{msg}]"
end


#and_spec = File.open("and_spec.rb")
SPECS.each do |spec|
  $stderr.puts "===================================="
  $stderr.puts "Running [#{spec}]"
  `./bin/convert #{spec}`
  load "./tmp/#{spec.gsub("/", "_")}"
  $stderr.puts "\nOk! Passed #{@test_count}, failed #{@fails}"
  $stderr.puts "===================================="
end
$stderr.puts "\n"
